# Generated by Django 3.1.3 on 2022-09-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Expiredate',
            new_name='expiredate',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Joindate',
            new_name='joindate',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Plan',
            new_name='plan',
        ),
    ]
